version: '3.3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.31
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: grv3
      MYSQL_USER: grv3
      MYSQL_PASSWORD: grv3
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: grv3
      PMA_PASSWORD: grv3
      PMA_ARBITRARY: 1

  redis:
    image: redis:6.0.9

  api:
    image: node:14.15.3
    command: bash start-api.sh
    ports:
      - 1337:1337
      - 9229:9229
    environment:
      sails_datastores__default__url: mysql://grv3:grv3@db:3306/grv3
      sails_session__url: redis://redis:6379
      sails_abr__guid: ${sails_abr__guid}
      sails_getstream__key: ${sails_getstream__key}
      sails_getstream__secret: ${sails_getstream__secret}
      sails_api2pdf__key: ${sails_api2pdf__key}
      sails_email__transporter__host: ${sails_email__transporter__host}
      sails_email__transporter__port: ${sails_email__transporter__port}
      sails_email__transporter__auth__user: ${sails_email__transporter__auth__user}
      sails_email__transporter__auth__pass: ${sails_email__transporter__auth__pass}
    volumes:
      - ./api:/api
      - ./.eslintrc:/.eslintrc
      - ./start-api.sh:/start-api.sh
    depends_on:
      - redis
      - db

  client:
    image: node:14.15.3
    command: bash start-client.sh
    environment:
      API_URL: http://api:1337
      GETSTREAM_KEY: ${sails_getstream__key}
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - ./.eslintrc:/.eslintrc
      - ./start-client.sh:/start-client.sh
    depends_on:
      - api

  stripe-cli:
    image: stripe/stripe-cli:v1.5.9
    command: --api-key sk_test_HuBC6LeSantmu3dZdEB4Rxtd000INtAkul listen --forward-to http://api:1337/stripe/webhook
    depends_on:
    - api
