
module.exports = [
  {
    'id': 1,
    'key': 'multiOrgs',
    'value': 'true',
    'inputType': 'bool',
    'desc': 'Indicates if the site has only one main org, or multi',
    'clientSafe': true
  },
  {
    'id': 2,
    'key': 'defaultOrg',
    'value': '1',
    'inputType': 'text',
    'desc': 'The ID (number) of the default org',
    'clientSafe': true
  },
  {
    'id': 3,
    'key': 'listLimitDefault',
    'value': '20',
    'inputType': 'text',
    'protected': false,
    'desc': 'Default number of rows showing in a table'
  },
  {
    'id': 4,
    'key': 'emailUser',
    'value': 'kindtk5@gmail.com',
    'inputType': 'text',
    'protected': false,
    'desc': 'Email setup: username'
  },
  {
    'id': 5,
    'key': 'emailPass',
    'value': 'cypeuqtyqqieizma',
    'inputType': 'text',
    'protected': false,
    'desc': 'Email setup: password'
  },
  {
    'id': 6,
    'key': 'siteTypes',
    'value': 'complaints',
    'data': 'complaints,mediations',
    'inputType': 'dropdown',
    'desc': 'Allowed dispute types in this site,' +
      ' can only be mediation and/or complaint' +
      ' (lower case and no typos!)',
    'clientSafe': true
  },
  {
    'id': 7,
    'key': 'systemEmailSignature',
    'value': '<hr>Thanks,<br>The Guided Resolution Team',
    'inputType': 'html',
    'protected': false,
    'desc': 'Email setup: default email signature' +
      ' (for all emails generated by the system)'
  },
  {
    'id': 8,
    'key': 'stripeSecretKey',
    'value': 'sk_test_HuBC6LeSantmu3dZdEB4Rxtd000INtAkul',
    'inputType': 'text',
    'desc': 'Stripe secret key'
  },
  {
    'id': 9,
    'key': 'siteName',
    'value': 'Guided Resolution',
    'inputType': 'text',
    'desc': 'Site Name',
    'clientSafe': true
  },
  {
    'id': 10,
    'key': 'stripePlansIDs',
    'value': JSON.stringify([
      {
        id: 1,
        price: '$99 p.m',
        priceId: 'price_1IGfXyCqgyRei99md8UMtFsN',
        name: 'Be Ready',
        slug: 'be-ready'
      },
      {
        id: 2,
        price: '$499 p.m',
        priceId: 'price_1IGfZ4CqgyRei99mV9njXUNN',
        name: 'Be Safe',
        slug: 'be-safe'
      }
    ]),
    'inputType': 'text',
    'clientSafe': true,
    'desc': 'Stripe Plan IDS, JSON array'
  }
];
